name: Build and Deploy

on:
  push:
    branches:
      - main
env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build -- --no-warnings

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: my-app-artifact
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-app-artifact
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN  }}
          artifact_name: my-app-artifact  # Update artifact name to match the uploaded artifact
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          preview: false

permissions:
  id-token: write
